default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - id: prospector
        name: prospector
        entry: python -m prospector.__main__
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.25.0
    hooks:
      - id: yapf
  - repo: https://github.com/prettier/prettier
    rev: "1.16.4"
    hooks:
      - id: prettier
