version: "3.7"
services:
  django:
    container_name: django
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - ./confero:/code/confero
      - ./fec:/code/fec
      - ./htmlcov:/code/htmlcov
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: confero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5439:5432"

volumes:
  postgres_data:
