version: "3"
services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./manage.py:/manage.py
      - ./confero:/confero
      - ./bin:/bin
      - ./htmlcov:/htmlcov
      - ./.coveragerc:/.coveragerc
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: confero
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: