branch-defaults:
  chores/awsdb:
    environment: confero-env
  chores/circleci:
    environment: confero-env
    group_suffix: null
  master:
    environment: confero-env
environment-defaults:
  confero-env:
    branch: null
    repository: null
global:
  application_name: project-confero
  branch: null
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  target: prod
  workspace_type: Application
