version: 2

jobs:

  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Container from Dockerfile
          command: docker build -t confero . # install requirements
      - run: echo 'Run the tests....'
      - run:
          filters:
            branches:
              only:
                - master
          name: Deploy to Elastic Beanstalk Environment
          command: |
          pip install --upgrade awsebcli
          eb deploy confero-env
