version: 2

jobs:

  build:
    docker:
      - image: cgarretty/confero:latest
    steps:
      - run: echo {AWS_ACCESS_KEY_ID}
      - run:
          name: Initialize Elastic Beanstalk
          command:
              eb init -p docker project-confero
      - deploy:
          filters:
            branches:
              only:
                - chores/circleci
                - master
          name: Deploy to Elastic Beanstalk Environment
          command: eb deploy
