version: 2

jobs:

  build:
    docker:
      - image: cgarretty/confero:latest
    steps:
      - run: echo 'Run the tests....'
      - deploy:
          filters:
            branches:
              only:
                - master
          name: Deploy to Elastic Beanstalk Environment
          command: eb deploy confero-env
