version: 2

jobs:

  test:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Container from Dockerfile
          command: docker build -t confero . # install requirements
      - run: echo 'Run the tests....'

  deploy:
    docker:
      - image: python:3.7-alpine
    steps:
      - run:
          filters:
            branches:
              only:
                - master
          name: Deploy to Elastic Beanstalk Environment
          command: eb deploy confero-env

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
