version: 2

jobs:

  test:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          requires:
            - setup_remote_docker
          name: Build Container from Dockerfile
          command: docker build -t confero . # install requirements
      - run: echo 'Run the tests....'

  deploy:
    docker:
      - image: python:3.7-alpine
    steps:
      - run:
          filters:
            branches:
              only:
                - master
          name: Deploy to Elastic Beanstalk Environment
          command: eb deploy confero-env

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
