version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/confero/confero-front

    steps:
      - checkout:
          path: ~/confero

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn lint
      - run: yarn test

      - deploy:
          name: Deploy to Surge
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              yarn build
              yarn deploy
            fi
