version: 2

jobs:

  build:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run: echo 'Run the tests....'
      - run:
          name: Initialize Elastic Beanstalk
          command:
              eb init -p docker project-confero
      - deploy:
          filters:
            branches:
              only:
                - chores/circleci
                - master
          name: Deploy to Elastic Beanstalk Environment
          command: eb deploy --region us-east-2
