version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres
        environment:
          DB_DB_NAME: confero
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_HOSTNAME: localhost
          DB_PORT: 5439
    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev --system

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      - run: bash ./bin/lint
      - run: bash ./bin/coverage
      - store_artifacts:
          path: ./htmlcov
          destination: coverage
      - run:
          name: Initialize Elastic Beanstalk
          command: eb init -p docker project-confero
      - deploy:
          name: Deploy to Elastic Beanstalk Environment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              eb deploy --region us-east-2
            fi
