version: 2

jobs:

  build:
    docker:
      - image: cgarretty/confero
    steps:
      - checkout
      - run:
          name: Build Container from Dockerfile
          command: docker build -t confero . # install requirements
      - run: echo 'Run the tests....'
      - run:
          filters:
            branches:
              only:
                - master
          name: Deploy to Elastic Beanstalk Environment
          command:
            eb deploy confero-env
