# Generated by Django 2.1.5 on 2019-02-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id',
                 models.CharField(
                     max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('office',
                 models.CharField(
                     choices=[('H', 'House'), ('S', 'Senate'),
                              ('P', 'President')],
                     max_length=1)),
                ('party', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=2)),
                ('district', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='politician',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='fec.Politician'),
        ),
    ]
