# Generated by Django 2.1.7 on 2019-02-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('contributor_name', models.CharField(max_length=200)),
                ('contributor_city', models.CharField(max_length=30)),
                ('contributor_state', models.CharField(max_length=2)),
                ('contributor_zip', models.CharField(max_length=9)),
                ('contributor_employer', models.CharField(max_length=38)),
                ('contributor_occupation', models.CharField(max_length=38)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fec.Committee')),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='politician',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Politician',
        ),
        migrations.AddField(
            model_name='committee',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fec.Campaign'),
        ),
    ]
