# Generated by Django 2.1.7 on 2019-02-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0002_auto_20190225_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
