# Generated by Django 2.1.7 on 2019-03-14 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0003_auto_20190225_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=200)),
                ('contributor_city', models.CharField(max_length=30)),
                ('contributor_state', models.CharField(max_length=2)),
                ('contributor_zip', models.CharField(max_length=9)),
                ('contributor_employer', models.CharField(max_length=38)),
                ('contributor_occupation', models.CharField(max_length=38)),
            ],
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contributor_city',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contributor_employer',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contributor_name',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contributor_occupation',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contributor_state',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contributor_zip',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='fec.Contributor'),
        ),
    ]
