# Generated by Django 2.2.1 on 2019-10-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0004_auto_20190314_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_connections', to='fec.Campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_connections', to='fec.Campaign')),
            ],
        ),
    ]
